### ISSUE TITLE
check_formulas() doesn't work with > 2 terms in formula

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#48]
Need to replace:

deciding_condition <- labels(f)[-1]

with:

deciding_condition <- labels(f) %>% tail(1)

**Comment by hxin** [comment]
fixed d4786f5845989e425244b279dc79c887dd9e3052

**Comment by lweasel** [comment]
Hmm, I think this is still not working, e.g. in the current code if labels(f) equals c("cond1", "cond2", "cond3") then

deciding_condition <- labels(f)[-1]

sets deciding_condition to c("cond2", "cond3"). Whereas

deciding_condition <- labels(f) %>% tail(1)

would set deciding_condition to c("cond3") as desired.
